### ISSUE TITLE
Error upon building: CGFloat cast issue

### ISSUE THREAD

**Issue by wbashir** [ataugeron/SpriteKit-Spring#2]
Thanks for the 'package'. I am getting an error when I tried building my project after adding this `pod` 

`SpriteKit-Spring/SpriteKit-Spring.swift:240:62: 'AnyObject?' is not convertible to 'CGFloat'; did you mean to use 'as!' to force downcast?`

**Comment by wbashir** [comment]
Now that I have looked at the other issues, this might be similar to #1 and related to an upgrade of Swift 1.2

**Comment by ataugeron** [comment]
Indeed, I merged the PR but didn't update the pod. Should be good now.
