### ISSUE TITLE
var parameters are depreciated and will be removed in swift 3.

### ISSUE THREAD

**Issue by dkliman** [ataugeron/SpriteKit-Spring#4]
`private class func animateKeyPath(keyPath: String, **var** byValue initialDistance: CGFloat!, **var** toValue finalValue: CGFloat!, duration: NSTimeInterval, delay: NSTimeInterval, usingSpringWithDamping dampingRatio: CGFloat, initialSpringVelocity velocity: CGFloat) -> SKAction {`

`var initialDistance  = byValue`
`var finalValue  = toValue`
would it be ok to create local variables from the immutable ones that would be in the parameters, perhaps?

**Comment by ataugeron** [comment]
Sure, that's probably more readable too. Do you want to make a pull
request? :-)

**Comment by dkliman** [comment]
Oh I also had another problem... The spring action was nothing like apple's and an SKLabelNode   that I move from off screen bounces wildly instead of just springing a little at the end... I need to send you some sample code... Maybe. Address that before making a pull request... I'll send from my laptop a little later....

**Comment by dkliman** [comment]
sorry but I had made a few typos on that message and the corrected version is on the site. but sure, why not. it’s a minor change though..

**Comment by ataugeron** [comment]
Fixed by #5
