### ISSUE TITLE
Objective-C Version?

### ISSUE THREAD

**Issue by KjellConnelly** [ataugeron/SpriteKit-Spring#6]
Any way you could translate this to Objective-C? I really want to use Spring Animations, but my Swift knowledge is sparse, and would take a lot more time than I would want to figure out how to write it myself. If not, that's okay, but I thought I would ask as it would probably be helpful for others as well who still use Obj-C. Thanks!

**Comment by AverageHelper** [comment]
No need! Apple has already thought of this, and this code will compile just fine under any modern Xcode compiler, and run from Swift or Objective-C wherever you want to call it!

Link: http://lmgtfy.com/?q=swift+and+objective-c

**Comment by warpling** [comment]
No need to be lmgtfy-condescending @SparrowBlaze.
The extensions needed `public` added to them: PR #13.
