### ISSUE TITLE
Chaining/Grouping/Sequencing?

### ISSUE THREAD

**Issue by damirstuhec** [ataugeron/SpriteKit-Spring#7]
@ataugeron can this actions be chained/grouped/sequenced together just like basic `SKAction`s can be?

**Comment by ataugeron** [comment]
Absolutely, you can use SKAction.sequence and SKAction.group. However,
since this action is implemented with SKAction.customActionWithDuration,
you cannot reverse it (reversedAction will just return the same action).

**Comment by damirstuhec** [comment]
Ok, great. Thanks!
